### ISSUE TITLE
[StopIteration Error] PyVCF Package

### ISSUE THREAD

**Issue by saisomesh2594** [fasterius/VarClust#1]
Hey,

I have been trying to implement VarClust on the VCF files for my samples. These VCF files were called using GATK and contain headers. However, running **varclust_create_profiles** gives a StopIteration error - essentially meaning the end of file has been reached .... I checked the lines which cause the error and it seems to generate from the Reader class in the PyVCF python package... So, I was wondering if there is a specific format of the VCF files which you used (headerless or something else?)

Any help would be highly appreciated!

Thanks

**Comment by fasterius** [comment]
Hi,

The VCF files analysed by VarClust do have headers, and they have also been generated using GATK (HaplotypeCaller), so I am not sure why you are getting your error. Could you send me a subset of a VCF that gives you the error, so that I may do some troubleshooting?

**Comment by saisomesh2594** [comment]
Hi!,

Thanks for your reply. 

You can take a look at the vcf files I am using from [here](https://mdcsft.mdc-berlin.de/download.php/1682480626/vcfs.zip)

**Comment by fasterius** [comment]
You are getting the error because your VCFs are malformed: your samples are specified as `0`, rather than as `060_S1_snv` and `123_S6_snv`. The sample in VCF files are specified in the last column, and you will either need to change those to correspond to the filename.

Additionally, since your VCFs are not annotated with snpEff, you will also need to use the flag `--method position_only`.

**Comment by fasterius** [comment]
I have now clarified this naming scheme in the documentation, which will hopefully help future users. Thanks for bringing this to my attention!
